name: Testing 123

on:
  workflow_dispatch:
  push:

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: sudo apt install -y ghostscript graphviz-dev texlive-latex-base texlive-fonts-recommended texlive-fonts-extra
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
      - run: python3 -m pip install pandoc plastex git+https://github.com/PatrickMassot/leanblueprint

      - name: Loop
        run: |
          mkdir pages
          for sha in $(git rev-list --all)
          do
            git switch --detach --force --quiet $sha
            if [[ -e blueprint ]]; then
              cd blueprint/src
              if plastex -c plastex.cfg web.tex; then
                cp -r ../web/ "${{ github.workspace }}/pages/$(git show -s --format=%ci $sha | cut -d' ' -f1)/"
              fi
              cd ${{ github.workspace }}
            fi
          done


      - uses: actions/upload-artifact@v3
        with:
          name: pages
          path: pages
